    name: Example key vault flow

    on: [push]

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - uses: actions/checkout@v2
        - uses: Azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - uses: Azure/get-keyvault-secrets@v1
          with: 
            keyvault: "myfirstwebappkv-kms"
            secrets: 'Zwy2e60IUllR0XvTj1PTPA3VXN0OaW2flNt9hsD/Sx+ACRCgel3O, ovLGLFKuz+wejWDN9ejSSw7EqiUl9UVcrCzeJSPU4j+ACRByEHin'
          id: myGetSecretAction
        - uses: azure/docker-login@v1
          with:
            login-server: ${{ steps.myGetSecretAction.outputs.containerUsername }}.azurecr.io
            username: ${{ steps.myGetSecretAction.outputs.containerUsername }}
            password: ${{ steps.myGetSecretAction.outputs.containerPassword }}
